// Builds each widget into one self-contained HTML file (inline JS and CSS) and
// writes it as a TypeScript string module the MCP server can import. Run with
// `npm run build:widgets`; the output in lib/mcp/ui/generated is committed.

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'vite'
import { viteSingleFile } from 'vite-plugin-singlefile'

const root = resolve(fileURLToPath(import.meta.url), '../..')
const widgets = ['app']
const outDir = join(root, 'lib/mcp/ui/generated')
mkdirSync(outDir, { recursive: true })

for (const name of widgets) {
  const tmp = mkdtempSync(join(tmpdir(), `widget-${name}-`))
  await build({
    root: join(root, 'widgets', name),
    configFile: false,
    logLevel: 'warn',
    plugins: [viteSingleFile()],
    resolve: { alias: { '@': root } },
    build: {
      outDir: tmp,
      emptyOutDir: true,
      minify: true,
      target: 'es2020',
      cssCodeSplit: false,
    },
  })
  const html = readFileSync(join(tmp, 'index.html'), 'utf8')
  rmSync(tmp, { recursive: true, force: true })
  const file = join(outDir, `${name}.ts`)
  writeFileSync(
    file,
    `// Generated by scripts/build-widgets.mjs from widgets/${name}. Do not edit.\n` +
      `export const html = ${JSON.stringify(html)}\n`
  )
  console.log(`${name}: ${(html.length / 1024).toFixed(1)} kB`)
}
